repo: dongitran/CDS-Debug
environment: null
type: secret

secrets:
  # VS Code Marketplace Personal Access Token — used to publish the extension via `vsce publish`
  # Bitwarden: Token/
  - name: VSCE_PAT
    bitwarden: VSCE_PAT
