export const CF_DEFAULT_SPACE = 'app';

export interface CredentialStatus {
  hasCredentials: boolean;
  email: string;
  /** 'env' = process.env or login-shell, 'keychain' = VS Code SecretStorage, 'none' = not set */
  source: 'env' | 'keychain' | 'none';
}

// Schema for the optional per-project config file (cap-debug-config.json).
export interface CapDebugConfig {
  remoteRoot?: string;
  /** Per-service branch override — takes priority over orgBranchMap. */
  branch?: string;
  /** Maps CF org name to the git branch that should be checked out before debugging. */
  orgBranchMap?: Record<string, string>;
  /** Replaces the default outFiles glob list when present. */
  outFiles?: string[];
  /** Appended to the default outFiles glob list when outFiles is not set. */
  outFilesExtra?: string[];
  /**
   * Overrides the default `resolveSourceMapLocations: null`. Use `null` to keep
   * the workspace-only filter disabled, or pass an explicit glob list.
   */
  resolveSourceMapLocations?: string[] | null;
  /** Path-mapping overrides merged on top of the extension defaults. */
  sourceMapPathOverrides?: Record<string, string>;
}

export type BranchPrepStep =
  | 'pending'
  | 'stashing'
  | 'checking-out'
  | 'pulling'
  | 'installing'
  | 'building'
  | 'done'
  | 'skipped'
  | 'error';

export interface BranchPrepService {
  appName: string;
  targetBranch: string;
  currentBranch: string;
}

export const CACHE_TTL_MS = 4 * 60 * 60 * 1000;

export const DEBUG_BASE_PORT = 20000;

export type CfAppState = 'started' | 'stopped' | 'empty';

export interface CfApp {
  name: string;
  state: CfAppState;
  urls?: string[];
}

export interface OrgGroupMapping {
  cfOrg: string;
  /** Missing in legacy configs; treated as CF_DEFAULT_SPACE. */
  cfSpace?: string;
  groupFolderPath: string; // absolute path to the local group folder
}

export interface DebugTarget {
  appName: string;
  folderPath: string;
  port: number;
  /** True when folderPath is a workspace fallback — no matching local source folder was found. */
  noLocalFolder?: boolean;
}

export interface LaunchConfiguration {
  type: string;
  request: string;
  name: string;
  address: string;
  port: number;
  localRoot: string;
  remoteRoot?: string;
  /**
   * Marker for configurations generated by this extension.
   * Unknown launch properties are ignored by VS Code and let us safely
   * distinguish CDS-managed entries from user-defined configs.
   */
  cdsDebugManaged?: boolean;
  sourceMaps: boolean;
  /**
   * Optional. Omitted by default because the extension manages tunnel/session
   * recovery itself via processManager.scheduleReconnect; setting `restart: true`
   * causes vscode-js-debug to retry attach in parallel with our own reconnect,
   * which races against port re-binding and breakpoint state.
   */
  restart?: boolean;
  skipFiles: string[];
  outFiles: string[];
  /**
   * `null` disables the default workspace-only filter. Required for attach-mode
   * debugging through SSH tunnels because source maps embed remote paths
   * (e.g. /home/vcap/app/...) that fall outside the workspace and would
   * otherwise be silently dropped. See microsoft/vscode-js-debug#759.
   */
  resolveSourceMapLocations?: string[] | null;
  /**
   * Optional path-mapping overrides merged on top of vscode-js-debug's defaults.
   * Used to map remote source-map paths (e.g. /home/vcap/app/*) onto local
   * workspace paths when the standard remoteRoot/localRoot rule is not enough.
   */
  sourceMapPathOverrides?: Record<string, string>;
  /**
   * When true, vscode-js-debug attaches a sub-debugger to child processes spawned
   * by the attached Node process. Required for SAP CAP MTX sidecar (`@sap/cds-mtxs`),
   * worker_threads, and cluster workers — without this, breakpoints in child code
   * never bind even when the parent's breakpoints work.
   */
  autoAttachChildProcesses?: boolean;
}

export interface LaunchJson {
  version: string;
  configurations: LaunchConfiguration[];
}

export interface ExtensionConfig {
  apiEndpoint: string;
  orgs: string[];
  orgGroupMappings: OrgGroupMapping[];
}

export interface CfOrgCache {
  apps: CfApp[];
  cachedAt: number;
}

export interface CfRegionCache {
  apiEndpoint: string;
  orgs: string[];
  appsByOrg: Record<string, CfOrgCache>;
  lastSyncedAt: number;
}

export interface SyncProgress {
  isRunning: boolean;
  startedAt?: number;
  lastCompletedAt?: number;
  // Explicitly allow undefined so spread resets like `{ ...p, currentOrg: undefined }`
  // are valid under exactOptionalPropertyTypes: true.
  currentRegion?: string | undefined;
  currentOrg?: string | undefined;
  done: number;
  total: number;
}

/**
 * One Cloud Foundry org entry as discovered by cf-sync's structure file.
 * Powers the cross-region org search shown on the CF Region step.
 */
export interface CfTopologyOrg {
  regionKey: string;
  regionLabel: string;
  apiEndpoint: string;
  orgName: string;
  spaces: string[];
}

export interface CfTopology {
  /** True when cf-sync has finished a sync at least once and produced at least one accessible org. */
  ready: boolean;
  accounts: CfTopologyOrg[];
}

export interface CacheSettings {
  enabled: boolean;
  intervalHours: number;
}

export const DEFAULT_CACHE_SETTINGS: CacheSettings = {
  enabled: true,
  intervalHours: 24,
};

/** User-facing debug behavior preferences (separate from cache settings). */
export interface DebugPreferences {
  /**
   * When true, the Chrome DevTools inspector URL is opened automatically as
   * soon as a debug session reaches the ATTACHED state. Default: false.
   */
  openBrowserOnAttach: boolean;
  /**
   * When true, CDS Debug intercepts breakpoint stops to capture a snapshot,
   * then applies the current auto-continue behavior. When false, CDS Debug
   * does not handle breakpoint stops at all (native debugger pause behavior).
   * Default: false.
   */
  enableBreakpointSnapshotHandling: boolean;
  /**
   * When true, the branch auto-checkout feature is enabled: before starting
   * a debug session the extension stashes local changes, checks out the mapped
   * branch, then runs `pnpm i --shamefully-hoist` and `pnpm build`.
   * This is an experimental / potentially destructive operation. Default: false.
   */
  enableBranchPrep: boolean;
}

export const DEFAULT_DEBUG_PREFERENCES: DebugPreferences = {
  openBrowserOnAttach: false,
  enableBreakpointSnapshotHandling: false,
  enableBranchPrep: false,
};

export interface DebugSessionPackagePreferences {
  packageNameFilterRegex: string;
}

export const DEFAULT_DEBUG_SESSION_PACKAGE_PREFERENCES: DebugSessionPackagePreferences = {
  packageNameFilterRegex: '',
};

export type BreakpointStopReason = 'breakpoint';

export interface BreakpointContextVariable {
  name: string;
  value: string;
  type?: string;
  children?: BreakpointContextVariable[];
}

export interface BreakpointContextScope {
  name: string;
  expensive: boolean;
  variables: BreakpointContextVariable[];
}

export interface BreakpointContextLocation {
  sourcePath: string;
  line: number;
  column: number;
  functionName?: string;
}

export interface BreakpointContextSnapshot {
  id: string;
  appName: string;
  sessionName: string;
  reason: BreakpointStopReason;
  createdAt: number;
  threadId?: number;
  autoResumed: boolean;
  location?: BreakpointContextLocation;
  scopes: BreakpointContextScope[];
  captureError?: string;
}

export interface LoadedPackageSource {
  name?: string;
  path?: string;
  sourceReference?: number;
  origin?: string;
  presentationHint?: string;
  debugSessionId?: string;
  debugSessionName?: string;
}

export interface LoadedPackageFileMatch {
  kind: 'path' | 'content';
  line?: number;
  column?: number;
  preview?: string;
}

export interface LoadedPackageFile {
  id: string;
  label: string;
  relativePath: string;
  source: LoadedPackageSource;
  match?: LoadedPackageFileMatch;
}

export interface LoadedPackageFolderNode {
  id: string;
  kind: 'folder';
  name: string;
  path: string;
  children: LoadedPackageTreeNode[];
}

export interface LoadedPackageLeafNode {
  id: string;
  kind: 'file';
  name: string;
  path: string;
  file: LoadedPackageFile;
}

export type LoadedPackageTreeNode = LoadedPackageFolderNode | LoadedPackageLeafNode;

export interface LoadedPackageEntry {
  id: string;
  name: string;
  displayName: string;
  version?: string;
  files: LoadedPackageFile[];
  tree: LoadedPackageTreeNode[];
}

export interface PackageSourceLocation {
  line: number;
  column?: number;
}

export type E2eLoadedSourcesPlanStep =
  | {
    kind: 'packages';
    delayMs?: number;
  }
  | {
    kind: 'empty';
    delayMs?: number;
  }
  | {
    kind: 'error';
    delayMs?: number;
    message: string;
  }
  | {
    kind: 'hang';
  };

export interface E2eSessionAvailability {
  childSessionDelayMs?: number;
}

export type E2eBridgeCommand =
  | {
    action: 'EMIT_DEBUG_CONNECTING';
    payload: { appNames: string[]; ports: Record<string, number>; unmappedApps?: string[] };
  }
  | {
    action: 'EMIT_APP_DEBUG_STATUS';
    payload: { appName: string; status: string; message?: string };
  }
  | {
    action: 'SET_PACKAGE_FIXTURE';
    payload: {
      appName: string;
      packages: LoadedPackageEntry[];
      loadedSourcesPlan?: E2eLoadedSourcesPlanStep[];
      localRoot?: string;
      sessionAvailability?: E2eSessionAvailability;
    };
  }
  | {
    action: 'CLEAR_PACKAGE_FIXTURES';
  }
  | {
    action: 'SET_CREDENTIAL_STATUS_OVERRIDE';
    payload: { credentialStatus: CredentialStatus };
  }
  | {
    action: 'CLEAR_CREDENTIAL_STATUS_OVERRIDE';
  };

// Messages from webview → extension
export type WebviewMessage =
  | { type: 'SELECT_GROUP_FOLDER' }
  | { type: 'LOGIN'; payload: { apiEndpoint: string } }
  | { type: 'LOAD_SPACES'; payload: { org: string } }
  | { type: 'LOAD_APPS'; payload: { org: string; space?: string; forceRefresh?: boolean } }
  | { type: 'START_DEBUG'; payload: { appNames: string[]; org: string; space?: string } }
  | { type: 'STOP_DEBUG'; payload: { appName: string } }
  | { type: 'STOP_ALL_DEBUG' }
  | { type: 'OPEN_APP_URL'; payload: { url: string; source: 'manual' | 'auto' } }
  | { type: 'SAVE_MAPPINGS'; payload: { mappings: OrgGroupMapping[] } }
  | { type: 'LOAD_CONFIG' }
  | { type: 'RESET_LOGIN' }
  | { type: 'TRIGGER_SYNC' }
  | { type: 'GET_SYNC_STATUS' }
  | { type: 'GET_CACHE_CONFIG' }
  | { type: 'SAVE_CACHE_CONFIG'; payload: CacheSettings }
  | { type: 'GET_CF_TOPOLOGY' }
  | { type: 'GET_DEBUG_PREFS' }
  | { type: 'SAVE_DEBUG_PREFS'; payload: DebugPreferences }
  | { type: 'GET_DEBUG_SESSION_PACKAGE_PREFS' }
  | { type: 'SAVE_DEBUG_SESSION_PACKAGE_PREFS'; payload: DebugSessionPackagePreferences }
  | { type: 'REQUEST_CHANGE_MAPPING' }
  | { type: 'SAVE_CREDENTIALS'; payload: { email: string; password: string } }
  | { type: 'GET_CREDENTIALS_STATUS' }
  | { type: 'CLEAR_CREDENTIALS' }
  | { type: 'RETRY_DEBUG'; payload: { appName: string } }
  | { type: 'CLEAR_BREAKPOINT_SNAPSHOTS' }
  | { type: 'LOAD_PACKAGE_SOURCES'; payload: { appName: string } }
  | {
    type: 'SEARCH_PACKAGE_SOURCES';
    payload: { appName: string; query: string; requestId: number; packageNameFilterRegex?: string };
  }
  | {
    type: 'OPEN_PACKAGE_SOURCE';
    payload: { appName: string; source: LoadedPackageSource; location?: PackageSourceLocation };
  }
  | { type: 'E2E_BRIDGE'; payload: E2eBridgeCommand };

// Messages from logs webview → logs extension panel
export type LogsWebviewMessage =
  | { type: 'LOGS_GET_APPS' }
  | { type: 'LOGS_START'; payload: { appName: string } }
  | { type: 'LOGS_STOP'; payload: { appName: string } }
  | { type: 'LOGS_CLEAR'; payload: { appName: string } };

// Messages from logs extension panel → logs webview
export type LogsExtensionMessage =
  | { type: 'LOGS_APPS'; payload: { apps: string[]; streaming: string[] } }
  | { type: 'LOGS_LINE'; payload: { appName: string; line: string } }
  | { type: 'LOGS_STATUS'; payload: { appName: string; streaming: boolean } }
  | { type: 'LOGS_ERROR'; payload: { appName: string; message: string } };

// Messages from extension → webview
export type ExtensionMessage =
  | { type: 'GROUP_FOLDER_SELECTED'; payload: { path: string } }
  | { type: 'LOGIN_SUCCESS'; payload: { orgs: string[] } }
  | { type: 'LOGIN_ERROR'; payload: { message: string } }
  | { type: 'SPACES_LOADED'; payload: { org: string; spaces: string[] } }
  | { type: 'SPACES_ERROR'; payload: { org: string; message: string } }
  | { type: 'APPS_LOADED'; payload: { apps: CfApp[] } }
  | { type: 'APPS_ERROR'; payload: { message: string } }
  | { type: 'DEBUG_STARTED'; payload: { count: number } }
  | { type: 'DEBUG_CONNECTING'; payload: { appNames: string[]; ports: Record<string, number>; unmappedApps?: string[] } }
  | { type: 'APP_DEBUG_STATUS'; payload: { appName: string; status: string; message?: string } }
  | { type: 'DEBUG_ERROR'; payload: { message: string } }
  | { type: 'CONFIG_LOADED'; payload: { config: ExtensionConfig | null; activeSessions: Record<string, { status: string; message?: string }>; credentialStatus: CredentialStatus } }
  | { type: 'SYNC_STATUS'; payload: SyncProgress }
  | { type: 'CACHE_CONFIG'; payload: CacheSettings }
  | { type: 'CF_TOPOLOGY'; payload: CfTopology }
  | { type: 'DEBUG_PREFS'; payload: DebugPreferences }
  | { type: 'DEBUG_SESSION_PACKAGE_PREFS'; payload: DebugSessionPackagePreferences }
  | { type: 'BRANCH_PREP_START'; payload: { services: { appName: string; currentBranch: string; targetBranch: string }[] } }
  | { type: 'BRANCH_PREP_STATUS'; payload: { appName: string; step: BranchPrepStep; message?: string } }
  | { type: 'PROCEED_CHANGE_MAPPING' }
  | { type: 'CREDENTIALS_SAVED'; payload: { email: string; source: 'env' | 'keychain' | 'none' } }
  | { type: 'CREDENTIALS_ERROR'; payload: { message: string } }
  | { type: 'CREDENTIALS_STATUS'; payload: CredentialStatus }
  | { type: 'CREDENTIALS_REVOKED'; payload: { message: string } }
  | { type: 'BREAKPOINT_SNAPSHOTS'; payload: { snapshots: BreakpointContextSnapshot[] } }
  | { type: 'BREAKPOINT_SNAPSHOT_ADDED'; payload: { snapshot: BreakpointContextSnapshot } }
  | { type: 'PACKAGE_SOURCES_LOADED'; payload: { appName: string; packages: LoadedPackageEntry[] } }
  | {
    type: 'PACKAGE_SEARCH_RESULTS';
    payload: { appName: string; query: string; requestId: number; packages: LoadedPackageEntry[] };
  }
  | { type: 'PACKAGE_SOURCES_ERROR'; payload: { appName: string; message: string } };
