export const CF_DEFAULT_SPACE = 'app';

export interface CredentialStatus {
  hasCredentials: boolean;
  email: string;
  /** 'env' = process.env or login-shell, 'keychain' = VS Code SecretStorage, 'none' = not set */
  source: 'env' | 'keychain' | 'none';
}

// Schema for the optional per-project config file (cap-debug-config.json).
export interface CapDebugConfig {
  remoteRoot?: string;
  /** Per-service branch override — takes priority over orgBranchMap. */
  branch?: string;
  /** Maps CF org name to the git branch that should be checked out before debugging. */
  orgBranchMap?: Record<string, string>;
}

export type BranchPrepStep =
  | 'pending'
  | 'stashing'
  | 'checking-out'
  | 'pulling'
  | 'installing'
  | 'building'
  | 'done'
  | 'skipped'
  | 'error';

export interface BranchPrepService {
  appName: string;
  targetBranch: string;
  currentBranch: string;
}

export const CACHE_TTL_MS = 4 * 60 * 60 * 1000;

export const DEBUG_BASE_PORT = 20000;

export type CfAppState = 'started' | 'stopped' | 'empty';

export interface CfApp {
  name: string;
  state: CfAppState;
  urls?: string[];
}

export interface OrgGroupMapping {
  cfOrg: string;
  groupFolderPath: string; // absolute path to the local group folder
}

export interface DebugTarget {
  appName: string;
  folderPath: string;
  port: number;
  /** True when folderPath is a workspace fallback — no matching local source folder was found. */
  noLocalFolder?: boolean;
}

export interface LaunchConfiguration {
  type: string;
  request: string;
  name: string;
  address: string;
  port: number;
  localRoot: string;
  remoteRoot?: string;
  /**
   * Marker for configurations generated by this extension.
   * Unknown launch properties are ignored by VS Code and let us safely
   * distinguish CDS-managed entries from user-defined configs.
   */
  cdsDebugManaged?: boolean;
  sourceMaps: boolean;
  restart: boolean;
  skipFiles: string[];
  outFiles: string[];
}

export interface LaunchJson {
  version: string;
  configurations: LaunchConfiguration[];
}

export interface ExtensionConfig {
  apiEndpoint: string;
  orgs: string[];
  orgGroupMappings: OrgGroupMapping[];
}

export interface CfOrgCache {
  apps: CfApp[];
  cachedAt: number;
}

export interface CfRegionCache {
  apiEndpoint: string;
  orgs: string[];
  appsByOrg: Record<string, CfOrgCache>;
  lastSyncedAt: number;
}

export interface SyncProgress {
  isRunning: boolean;
  startedAt?: number;
  lastCompletedAt?: number;
  // Explicitly allow undefined so spread resets like `{ ...p, currentOrg: undefined }`
  // are valid under exactOptionalPropertyTypes: true.
  currentRegion?: string | undefined;
  currentOrg?: string | undefined;
  done: number;
  total: number;
}

export interface CacheSettings {
  enabled: boolean;
  intervalHours: number;
}

export const DEFAULT_CACHE_SETTINGS: CacheSettings = {
  enabled: true,
  intervalHours: 24,
};

/** User-facing debug behavior preferences (separate from cache settings). */
export interface DebugPreferences {
  /**
   * When true, the app URL is opened in the default browser automatically
   * as soon as a debug session reaches the ATTACHED state. Default: false.
   */
  openBrowserOnAttach: boolean;
  /**
   * When true, CDS Debug intercepts breakpoint stops to capture a snapshot,
   * then applies the current auto-continue behavior. When false, CDS Debug
   * does not handle breakpoint stops at all (native debugger pause behavior).
   * Default: false.
   */
  enableBreakpointSnapshotHandling: boolean;
  /**
   * When true, the branch auto-checkout feature is enabled: before starting
   * a debug session the extension stashes local changes, checks out the mapped
   * branch, then runs `pnpm i --shamefully-hoist` and `pnpm build`.
   * This is an experimental / potentially destructive operation. Default: false.
   */
  enableBranchPrep: boolean;
}

export const DEFAULT_DEBUG_PREFERENCES: DebugPreferences = {
  openBrowserOnAttach: false,
  enableBreakpointSnapshotHandling: false,
  enableBranchPrep: false,
};

export type BreakpointStopReason = 'breakpoint';

export interface BreakpointContextVariable {
  name: string;
  value: string;
  type?: string;
  children?: BreakpointContextVariable[];
}

export interface BreakpointContextScope {
  name: string;
  expensive: boolean;
  variables: BreakpointContextVariable[];
}

export interface BreakpointContextLocation {
  sourcePath: string;
  line: number;
  column: number;
  functionName?: string;
}

export interface BreakpointContextSnapshot {
  id: string;
  appName: string;
  sessionName: string;
  reason: BreakpointStopReason;
  createdAt: number;
  threadId?: number;
  autoResumed: boolean;
  location?: BreakpointContextLocation;
  scopes: BreakpointContextScope[];
  captureError?: string;
}

export interface LoadedPackageSource {
  name?: string;
  path?: string;
  sourceReference?: number;
  origin?: string;
  presentationHint?: string;
  debugSessionId?: string;
  debugSessionName?: string;
}

export interface LoadedPackageFile {
  id: string;
  label: string;
  relativePath: string;
  source: LoadedPackageSource;
}

export interface LoadedPackageFolderNode {
  id: string;
  kind: 'folder';
  name: string;
  path: string;
  children: LoadedPackageTreeNode[];
}

export interface LoadedPackageLeafNode {
  id: string;
  kind: 'file';
  name: string;
  path: string;
  file: LoadedPackageFile;
}

export type LoadedPackageTreeNode = LoadedPackageFolderNode | LoadedPackageLeafNode;

export interface LoadedPackageEntry {
  id: string;
  name: string;
  displayName: string;
  version?: string;
  files: LoadedPackageFile[];
  tree: LoadedPackageTreeNode[];
}

export type E2eBridgeCommand =
  | {
    action: 'EMIT_DEBUG_CONNECTING';
    payload: { appNames: string[]; ports: Record<string, number>; unmappedApps?: string[] };
  }
  | {
    action: 'EMIT_APP_DEBUG_STATUS';
    payload: { appName: string; status: string; message?: string };
  }
  | {
    action: 'SET_PACKAGE_FIXTURE';
    payload: { appName: string; packages: LoadedPackageEntry[] };
  }
  | {
    action: 'CLEAR_PACKAGE_FIXTURES';
  };

// Messages from webview → extension
export type WebviewMessage =
  | { type: 'SELECT_GROUP_FOLDER' }
  | { type: 'LOGIN'; payload: { apiEndpoint: string } }
  | { type: 'LOAD_APPS'; payload: { org: string } }
  | { type: 'START_DEBUG'; payload: { appNames: string[]; org: string } }
  | { type: 'STOP_DEBUG'; payload: { appName: string } }
  | { type: 'STOP_ALL_DEBUG' }
  | { type: 'OPEN_APP_URL'; payload: { url: string; source: 'manual' | 'auto' } }
  | { type: 'SAVE_MAPPINGS'; payload: { mappings: OrgGroupMapping[] } }
  | { type: 'LOAD_CONFIG' }
  | { type: 'RESET_LOGIN' }
  | { type: 'TRIGGER_SYNC' }
  | { type: 'GET_SYNC_STATUS' }
  | { type: 'GET_CACHE_CONFIG' }
  | { type: 'SAVE_CACHE_CONFIG'; payload: CacheSettings }
  | { type: 'GET_DEBUG_PREFS' }
  | { type: 'SAVE_DEBUG_PREFS'; payload: DebugPreferences }
  | { type: 'REQUEST_CHANGE_MAPPING' }
  | { type: 'SAVE_CREDENTIALS'; payload: { email: string; password: string } }
  | { type: 'GET_CREDENTIALS_STATUS' }
  | { type: 'CLEAR_CREDENTIALS' }
  | { type: 'RETRY_DEBUG'; payload: { appName: string } }
  | { type: 'CLEAR_BREAKPOINT_SNAPSHOTS' }
  | { type: 'LOAD_PACKAGE_SOURCES'; payload: { appName: string } }
  | { type: 'OPEN_PACKAGE_SOURCE'; payload: { appName: string; source: LoadedPackageSource } }
  | { type: 'E2E_BRIDGE'; payload: E2eBridgeCommand };

// Messages from logs webview → logs extension panel
export type LogsWebviewMessage =
  | { type: 'LOGS_GET_APPS' }
  | { type: 'LOGS_START'; payload: { appName: string } }
  | { type: 'LOGS_STOP'; payload: { appName: string } }
  | { type: 'LOGS_CLEAR'; payload: { appName: string } };

// Messages from logs extension panel → logs webview
export type LogsExtensionMessage =
  | { type: 'LOGS_APPS'; payload: { apps: string[]; streaming: string[] } }
  | { type: 'LOGS_LINE'; payload: { appName: string; line: string } }
  | { type: 'LOGS_STATUS'; payload: { appName: string; streaming: boolean } }
  | { type: 'LOGS_ERROR'; payload: { appName: string; message: string } };

// Messages from extension → webview
export type ExtensionMessage =
  | { type: 'GROUP_FOLDER_SELECTED'; payload: { path: string } }
  | { type: 'LOGIN_SUCCESS'; payload: { orgs: string[] } }
  | { type: 'LOGIN_ERROR'; payload: { message: string } }
  | { type: 'APPS_LOADED'; payload: { apps: CfApp[] } }
  | { type: 'APPS_ERROR'; payload: { message: string } }
  | { type: 'DEBUG_STARTED'; payload: { count: number } }
  | { type: 'DEBUG_CONNECTING'; payload: { appNames: string[]; ports: Record<string, number>; unmappedApps?: string[] } }
  | { type: 'APP_DEBUG_STATUS'; payload: { appName: string; status: string; message?: string } }
  | { type: 'DEBUG_ERROR'; payload: { message: string } }
  | { type: 'CONFIG_LOADED'; payload: { config: ExtensionConfig | null; activeSessions: Record<string, { status: string; message?: string }>; credentialStatus: CredentialStatus } }
  | { type: 'SYNC_STATUS'; payload: SyncProgress }
  | { type: 'CACHE_CONFIG'; payload: CacheSettings }
  | { type: 'DEBUG_PREFS'; payload: DebugPreferences }
  | { type: 'BRANCH_PREP_START'; payload: { services: { appName: string; currentBranch: string; targetBranch: string }[] } }
  | { type: 'BRANCH_PREP_STATUS'; payload: { appName: string; step: BranchPrepStep; message?: string } }
  | { type: 'PROCEED_CHANGE_MAPPING' }
  | { type: 'CREDENTIALS_SAVED'; payload: { email: string; source: 'env' | 'keychain' | 'none' } }
  | { type: 'CREDENTIALS_ERROR'; payload: { message: string } }
  | { type: 'CREDENTIALS_STATUS'; payload: CredentialStatus }
  | { type: 'CREDENTIALS_REVOKED'; payload: { message: string } }
  | { type: 'BREAKPOINT_SNAPSHOTS'; payload: { snapshots: BreakpointContextSnapshot[] } }
  | { type: 'BREAKPOINT_SNAPSHOT_ADDED'; payload: { snapshot: BreakpointContextSnapshot } }
  | { type: 'PACKAGE_SOURCES_LOADED'; payload: { appName: string; packages: LoadedPackageEntry[] } }
  | { type: 'PACKAGE_SOURCES_ERROR'; payload: { appName: string; message: string } };
